# Generated by Django 5.0.4 on 2024-04-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='Nazvanie_producta',
        ),
    ]
