# Generated by Django 5.0.4 on 2024-04-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_total_price_order_nazvanie_producta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Nazvanie_producta',
            new_name='car',
        ),
    ]
